<x-pdf with-header with-footer>
    <x-pdf-page>
        {{ $greeting }}, page 1
    </x-pdf-page>

    <x-pdf-page>
        {{ $greeting }}, page 2
    </x-pdf-page>

    <x-pdf-page>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at pulvinar est. Maecenas tortor ipsum, vulputate sed ligula vel, varius blandit ligula. Fusce mattis iaculis commodo. Mauris scelerisque dignissim posuere. Nam aliquet condimentum nisl eu sollicitudin. Pellentesque ut neque vestibulum, volutpat velit a, pulvinar nunc. Ut tortor diam, tincidunt et mauris eget, eleifend tristique lorem. Nam lobortis metus ligula, at vulputate ex imperdiet ac. Fusce et auctor enim, et mollis tellus. Phasellus dignissim iaculis risus non dictum.</p>
        <p>Proin at metus neque. Sed vitae ex dictum, iaculis leo sed, euismod diam. In sit amet felis fringilla, blandit risus sit amet, cursus sem. Cras posuere dolor enim, id varius diam commodo vel. Fusce molestie ipsum augue, ullamcorper posuere tortor tristique a. Duis finibus magna id tellus lacinia vulputate. Ut vel libero eu ligula pretium molestie. Integer malesuada ac lorem lobortis luctus. Ut in hendrerit libero. Duis in sem augue. Nam aliquet lorem id metus dapibus, gravida faucibus odio tincidunt. Proin tincidunt libero ac massa pretium luctus. Vestibulum rutrum pretium tellus quis sodales. Donec in volutpat dui, quis tristique risus. Aliquam id diam est.</p>
        <p>Pellentesque consequat lacus et pharetra venenatis. Aliquam vitae libero eget magna rhoncus scelerisque maximus eget libero. Integer malesuada quis massa vitae lobortis. Curabitur vitae arcu viverra, vulputate velit et, porttitor orci. Duis imperdiet ligula tellus, luctus pharetra augue elementum in. Nam euismod non velit id sagittis. Fusce sodales, sem at maximus ornare, eros augue lobortis libero, vel tempus nunc lacus eu mauris. Mauris finibus, eros non tempor iaculis, metus nisi pretium mi, vitae interdum lorem nisi id turpis. Donec et mauris gravida, congue diam vitae, interdum nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec enim vitae mauris lobortis convallis. Proin fermentum turpis sit amet rutrum viverra. Vestibulum accumsan finibus dictum. Morbi consectetur scelerisque lorem, at viverra augue lobortis ac.</p>
        <p>In ut nulla id mauris bibendum cursus sed quis ex. Phasellus consequat nunc ut metus viverra iaculis. Proin accumsan tristique purus, eget tempus ligula. Etiam lobortis mauris a eros feugiat, non ullamcorper dui venenatis. Aenean eros odio, convallis ut hendrerit ac, aliquet sit amet purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque id quam erat. Integer molestie non dui vel consectetur. Nam in bibendum lectus. Donec vel ullamcorper enim, sed dignissim dolor.</p>
        <p>Aenean euismod ut magna quis semper. Quisque finibus blandit justo at placerat. Duis fermentum erat ligula. Vestibulum vitae magna eros. Maecenas ultrices tellus quis dui mollis, sit amet lacinia risus molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed porta rhoncus odio a euismod. Mauris rutrum egestas finibus. Etiam fermentum rutrum venenatis. Duis molestie tellus nec nisi viverra cursus. Nullam egestas non elit et convallis. Mauris ligula eros, placerat nec sem nec, hendrerit viverra justo. Morbi euismod blandit placerat. Praesent ac quam massa. Nullam vitae diam vitae lorem elementum porttitor sed a dui.</p>
        <p>Integer vestibulum posuere elementum. In dapibus ligula a urna rutrum vehicula. Maecenas aliquam, lacus eu sodales luctus, mauris tortor vehicula tortor, id consectetur odio dui nec lectus. Phasellus dui erat, tempor quis mauris vel, porta vulputate risus. Etiam a turpis sed ipsum pellentesque suscipit. Donec arcu magna, congue vel velit in, condimentum accumsan tellus. Vivamus vitae faucibus erat. Ut sollicitudin ex nunc, eu ornare arcu ullamcorper et. Cras rutrum non nunc at pretium.</p>
        <p>Integer sapien sem, suscipit nec auctor in, convallis nec purus. Aliquam auctor nunc et justo pulvinar interdum. Nullam eu dignissim elit. Donec dui purus, luctus et libero sit amet, scelerisque tempor odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ullamcorper enim nunc, vel rhoncus nisi pretium at. Suspendisse ut pellentesque justo. Sed scelerisque augue vel leo sollicitudin viverra. Quisque dapibus ligula blandit nisl dapibus egestas. Morbi eu purus blandit, vehicula sem id, rutrum velit. Maecenas suscipit mi ut mollis congue. Fusce porta in orci sed volutpat. Vivamus mattis vestibulum iaculis. Fusce ullamcorper, metus non tincidunt sollicitudin, libero justo blandit magna, ac tempor est magna eu sem. Cras nec turpis eget sapien euismod sollicitudin.</p>
        <p>Donec iaculis sollicitudin sem sed lacinia. Etiam vitae convallis massa. Nullam non aliquet eros. Suspendisse potenti. Morbi malesuada id urna eu auctor. Donec at blandit justo, eget faucibus dolor. Suspendisse faucibus arcu quis lacus sodales, ac pellentesque velit ultricies. Pellentesque at sodales purus. Duis orci ex, condimentum ac laoreet vel, varius id tellus. Proin id justo lectus. Mauris at scelerisque erat, nec lobortis purus. Sed viverra mauris ut scelerisque condimentum. Vestibulum tempor orci magna, non congue turpis tristique at. Maecenas nec aliquam eros.</p>
        <p>Proin lacinia est in mattis tincidunt. Mauris pellentesque justo ut condimentum semper. Pellentesque at vulputate enim. Donec dictum nec nisl id ultricies. Donec mollis elit eget justo facilisis interdum. Cras nisi ante, elementum ac augue nec, efficitur tincidunt orci. Sed imperdiet nisi ex, efficitur pulvinar massa congue consectetur. In congue, enim non ultricies porttitor, turpis tortor consectetur urna, eget accumsan massa libero vitae turpis. Vivamus sodales libero vitae mattis varius. Pellentesque tempus risus in dui bibendum, nec molestie risus pulvinar.</p>
        <p>Ut a nibh ut arcu tristique malesuada. Donec ut tincidunt nunc. Etiam nec pretium elit, non posuere arcu. Vivamus augue justo, posuere quis tincidunt in, egestas id tellus. Vestibulum tristique gravida nulla sed hendrerit. Aenean rutrum dapibus eros, id lobortis magna scelerisque at. Mauris sed tincidunt augue. Nullam placerat nisi quis turpis lacinia, eget aliquet elit accumsan. Nullam interdum convallis ipsum non efficitur.</p>
    </x-pdf-page>
</x-pdf>
